### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by BadKoldrysh** [BadKoldrysh/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by BadKoldrysh** [comment]
@art-master009 Hi, please, help me with this issue. 🙏

**Comment by art-master009** [comment]
Use this sentences

**― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.**

**Comment by BadKoldrysh** [comment]
thanks
